### ISSUE TITLE
Authenticate with existing access token

### ISSUE THREAD

**Issue by chrstnbrn** [jfoshee/ServiceStack.Authentication.Aad#1]
I'm using your authentication provider with an ASP.NET MVC app which also uses Azure Active Directory. So I already have an access token and would like to use this token to authenticate with ServiceStack. Is this possible using the Authenticate request? If yes, how would this request look like?

**Comment by jfoshee** [comment]
Off the top of my head I don't think I have a one-liner to do that. I presume you need to validate that token w/ Microsoft to make sure it is good. (You might just be able to do a simple request like try fetching some demographic info).  Then you might take advantage of 
[`LoadUserAuthInfo`](https://github.com/jfoshee/ServiceStack.Authentication.Aad/blob/master/ServiceStack.Authentication.Aad/AadAuthProvider.cs#L327). See also the [handling of the access token](https://github.com/jfoshee/ServiceStack.Authentication.Aad/blob/master/ServiceStack.Authentication.Aad/AadAuthProvider.cs#L225) in the AuthProvider.

I'm sorry I couldn't be more helpful.
